title: "Jaki Gonzalez Spirit of Excellence Scholarship"
description: "Honoring Jaki Gonzalez by supporting Harvard High School seniors who embody excellence, resilience, and learning."
url: "https://jakigonzalezscholarship.org"
baseurl: ""  # must be empty since you're using a custom domain
markdown: kramdown
theme: null
permalink: pretty
exclude:
  - README.md
